### ISSUE TITLE
https://kernel-ci.emjay-embedded.co.uk/  is down!

### ISSUE THREAD

**Issue by aliceinwire** [gentoo/Gentoo_kernelCI#58]
please check what's wrong in you mirror

**Comment by mjeveritt** [comment]
PC running this seems to have suffered an unexplained failure. Since it also functions as my desktop PC I shall be investigating asap.... !

Hopefully I shall be porting this to my HP ProLiant server box in due course, but I thought I would try out the reverse-proxy to the existing instance to see how well it worked!

**Comment by aliceinwire** [comment]
still down?

**Comment by mjeveritt** [comment]
Back up now. Apologies for the delay!
